import '@/styles/globals.css';
import type { Metadata } from 'next';
import { cn } from '@/lib/utils/helpers';
import { Outfit } from 'next/font/google';
import Navbar from '@/components/common/navbar';
import TurbulenceNoise from '@/components/common/turbulence-noise';

const outFit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          outFit.className,
          'w-full h-full text-zinc-300 bg-neutral-900'
        )}
      >
        <TurbulenceNoise />
        <main className='max-w-[1200px] mx-auto md:py-10 px-4 min-h-[calc(100vh-50px-100px)] mb-10'>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
