import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import '@/styles/globals.css';
import Navbar from '@/components/common/navbar';
import { cn } from '@/lib/utils/helpers';

const outFit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          outFit.className,
          'w-full h-full text-zinc-300 bg-neutral-900'
        )}
      >
        <svg
          className='pointer-events-none fixed isolate z-50 opacity-70 mix-blend-soft-light'
          width='100%'
          height='100%'
        >
          <filter id='noise'>
            <feTurbulence
              type='fractalNoise'
              baseFrequency='0.80'
              numOctaves='4'
              stitchTiles='stitch'
            />
          </filter>
          <rect width='100%' height='100%' filter='url(#noise)' />
        </svg>
        <main className='max-w-[1000px] mx-auto md:py-10 px-4 min-h-[calc(100vh-50px-100px)] mb-10'>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
