import '@/styles/globals.css';
import type { Metadata } from 'next';
import { cn } from '@/lib/utils/helpers';
import { Toaster } from 'sonner';
import { Geist, Geist_Mono } from 'next/font/google';
import { NextAuthProvider } from '@/lib/providers/next-auth';
import { NavbarProgressProvider } from '@/lib/providers/loader';
import TurbulenceNoise from '@/components/common/turbulence-noise';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({children}: Readonly<{children: React.ReactNode}>) =>{
  return (
    <html lang='en'>
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          'w-full h-full text-zinc-300 bg-neutral-900 antialiased'
        )}
      >
        <NextAuthProvider>
          <TurbulenceNoise />
          <Toaster position='bottom-right' richColors />
          {children}
          <NavbarProgressProvider />
        </NextAuthProvider>
      </body>
    </html>
  );
}

export default RootLayout;