import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import '@/styles/globals.css';

const outFit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={outFit.className}>{children}</body>
    </html>
  );
}
